// 定义tinyFlash使用的Index列表
enum
{
    STORAGE_NAME = 1,
    STORAGE_BAUD,
    STORAGE_ATE,
    STORAGE_MODE,
    STORAGE_ADVDATA,
    STORAGE_LSLEEP,
    STORAGE_ADVINTV,
    STORAGE_RFPWR,
    STORAGE_IUUID,
    STORAGE_IMAJOR,
    STORAGE_IMONOR,
};